apiVersion: apps/v1 
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 8
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: shahin/up-running-kub-grpc:d2f18a03d66fd5fa92f265b6503aea313dae1fde
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: product-svc
    labels:
        app: product
spec:
    ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    selector:
     app: product
    type: ClusterIP