# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='product.proto',
  package='product',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rproduct.proto\x12\x07product\"u\n\x07Product\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x11\n\timageLink\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"\x1d\n\rGetProductReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\".\n\x0fListProductsReq\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"\x1b\n\x08HelloRes\x12\x0f\n\x07message\x18\x01 \x01(\t\"\n\n\x08HelloReq2\xf2\x01\n\x0eProductService\x12/\n\x05Hello\x12\x11.product.HelloReq\x1a\x11.product.HelloRes\"\x00\x12\x35\n\rCreateProduct\x12\x10.product.Product\x1a\x10.product.Product\"\x00\x12\x38\n\nGetProduct\x12\x16.product.GetProductReq\x1a\x10.product.Product\"\x00\x12>\n\x0cListProducts\x12\x18.product.ListProductsReq\x1a\x10.product.Product\"\x00\x30\x01\x62\x06proto3'
)




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='product.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='product.Product.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productName', full_name='product.Product.productName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='product.Product.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='product.Product.price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageLink', full_name='product.Product.imageLink', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='product.Product.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=143,
)


_GETPRODUCTREQ = _descriptor.Descriptor(
  name='GetProductReq',
  full_name='product.GetProductReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='product.GetProductReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=174,
)


_LISTPRODUCTSREQ = _descriptor.Descriptor(
  name='ListProductsReq',
  full_name='product.ListProductsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skip', full_name='product.ListProductsReq.skip', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='product.ListProductsReq.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=222,
)


_HELLORES = _descriptor.Descriptor(
  name='HelloRes',
  full_name='product.HelloRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='product.HelloRes.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=251,
)


_HELLOREQ = _descriptor.Descriptor(
  name='HelloReq',
  full_name='product.HelloReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=263,
)

DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['GetProductReq'] = _GETPRODUCTREQ
DESCRIPTOR.message_types_by_name['ListProductsReq'] = _LISTPRODUCTSREQ
DESCRIPTOR.message_types_by_name['HelloRes'] = _HELLORES
DESCRIPTOR.message_types_by_name['HelloReq'] = _HELLOREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.Product)
  })
_sym_db.RegisterMessage(Product)

GetProductReq = _reflection.GeneratedProtocolMessageType('GetProductReq', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTREQ,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.GetProductReq)
  })
_sym_db.RegisterMessage(GetProductReq)

ListProductsReq = _reflection.GeneratedProtocolMessageType('ListProductsReq', (_message.Message,), {
  'DESCRIPTOR' : _LISTPRODUCTSREQ,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.ListProductsReq)
  })
_sym_db.RegisterMessage(ListProductsReq)

HelloRes = _reflection.GeneratedProtocolMessageType('HelloRes', (_message.Message,), {
  'DESCRIPTOR' : _HELLORES,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.HelloRes)
  })
_sym_db.RegisterMessage(HelloRes)

HelloReq = _reflection.GeneratedProtocolMessageType('HelloReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQ,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:product.HelloReq)
  })
_sym_db.RegisterMessage(HelloReq)



_PRODUCTSERVICE = _descriptor.ServiceDescriptor(
  name='ProductService',
  full_name='product.ProductService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=266,
  serialized_end=508,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='product.ProductService.Hello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQ,
    output_type=_HELLORES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateProduct',
    full_name='product.ProductService.CreateProduct',
    index=1,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetProduct',
    full_name='product.ProductService.GetProduct',
    index=2,
    containing_service=None,
    input_type=_GETPRODUCTREQ,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListProducts',
    full_name='product.ProductService.ListProducts',
    index=3,
    containing_service=None,
    input_type=_LISTPRODUCTSREQ,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTSERVICE)

DESCRIPTOR.services_by_name['ProductService'] = _PRODUCTSERVICE

# @@protoc_insertion_point(module_scope)
