# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pb.product_pb2 as product__pb2


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/product.ProductService/Hello',
                request_serializer=product__pb2.HelloReq.SerializeToString,
                response_deserializer=product__pb2.HelloRes.FromString,
                )
        self.CreateProduct = channel.unary_unary(
                '/product.ProductService/CreateProduct',
                request_serializer=product__pb2.Product.SerializeToString,
                response_deserializer=product__pb2.Product.FromString,
                )
        self.GetProduct = channel.unary_unary(
                '/product.ProductService/GetProduct',
                request_serializer=product__pb2.GetProductReq.SerializeToString,
                response_deserializer=product__pb2.Product.FromString,
                )
        self.ListProducts = channel.unary_stream(
                '/product.ProductService/ListProducts',
                request_serializer=product__pb2.ListProductsReq.SerializeToString,
                response_deserializer=product__pb2.Product.FromString,
                )


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=product__pb2.HelloReq.FromString,
                    response_serializer=product__pb2.HelloRes.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=product__pb2.Product.FromString,
                    response_serializer=product__pb2.Product.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=product__pb2.GetProductReq.FromString,
                    response_serializer=product__pb2.Product.SerializeToString,
            ),
            'ListProducts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=product__pb2.ListProductsReq.FromString,
                    response_serializer=product__pb2.Product.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/Hello',
            product__pb2.HelloReq.SerializeToString,
            product__pb2.HelloRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/CreateProduct',
            product__pb2.Product.SerializeToString,
            product__pb2.Product.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductService/GetProduct',
            product__pb2.GetProductReq.SerializeToString,
            product__pb2.Product.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/product.ProductService/ListProducts',
            product__pb2.ListProductsReq.SerializeToString,
            product__pb2.Product.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
